import { IPseudoError } from "suman-types/dts/global";
import { ISumanConfig, ISumanOpts } from "suman-types/dts/global";
import { IAllOpts, ITestSuite } from "suman-types/dts/test-suite";
import { Suman } from "../suman";
import { ISumanServerInfo } from "suman-types/dts/suman";
export declare const handleSetupComplete: (test: ITestSuite, type: string) => void;
export declare const makeRequireFile: (projectRoot: string) => (v: string) => void;
export declare const extractVals: (val: any) => {
    timeout: number;
    subDeps: string[];
    fn: Function;
    props: string[];
};
export declare const makeHandleAsyncReporters: (reporterRets: any[]) => (cb: Function) => any;
export declare const makeRunGenerator: (fn: Function, ctx: any) => () => Promise<any>;
export declare const asyncHelper: (key: string, resolve: Function, reject: Function, $args: any[], ln: number, fn: Function) => any;
export declare const implementationError: (err: IPseudoError, isThrow?: boolean) => void;
export declare const loadSumanConfig: (configPath: string, opts: Object) => any;
export declare const resolveSharedDirs: (sumanConfig: ISumanConfig, projectRoot: string, sumanOpts: ISumanOpts) => any;
export declare const loadSharedObjects: (pathObj: Object, projectRoot: string, sumanOpts: ISumanOpts) => any;
export declare const vetPaths: (paths: string[]) => void;
export declare const fatalRequestReply: (obj: Object, $cb: Function) => any;
export declare const findSumanServer: (serverName?: string) => ISumanServerInfo;
export declare const makeOnSumanCompleted: (suman: Suman) => (code: number, msg: string) => void;
export declare const cloneError: (err: Error, newMessage: string, strip?: boolean) => IPseudoError;
export declare const parseArgs: (args: any[], fnIsRequired?: boolean) => {
    arrayDeps: IAllOpts[];
    args: any[];
};
export declare const evalOptions: (arrayDeps: IAllOpts[], opts: IAllOpts) => string[];
