version: 2.1

jobs:
  build-node22:
    resource_class: small
    docker:
      - image: cimg/node:22.14
    steps:
      - checkout
      - run:
          name: Build and test on Node 22
          command: ./scripts/circleci/run.sh

  build-node24:
    resource_class: small
    docker:
      - image: cimg/node:24.16.0
    steps:
      - checkout
      - run:
          name: Build and test on Node 24
          command: ./scripts/circleci/run.sh

workflows:
  build_nodejs:
    jobs:
      - build-node22
      - build-node24
