{
	"version": 2,
	"jobs": {
		"build": {
			"docker": [
				{
					"image": "circleci/node:10"
				}
			],
			"working_directory": "~/repo",
			"steps": [
				"checkout",
				{
					"restore_cache": {
						"keys": [
							"v1-dependencies-{{ checksum 'package.json' }}",
							"v1-dependencies-"
						]
					}
				},
				{
                  "run": "npm set prefix=/home/circleci/npm && echo 'export PATH=$HOME/circleci/npm/bin:$PATH' >> /home/circleci/.bashrc"
			    },
				{
                  "run": "npm install -g typescript && tsc || echo 'whatevs' "
                 },
				{
					"run": "npm install --loglevel=warn"
				},
				{
					"save_cache": {
						"paths": [
							"node_modules"
						],
						"key": "v1-dependencies-{{ checksum 'package.json' }}"
					}
				},
				{
					"run": "./scripts/circleci/run.sh"
				}
			]
		}
	}
}