'use strict';
Object.defineProperty(exports, "__esModule", { value: true });
const process = require('suman-browser-polyfills/modules/process');
const global = require('suman-browser-polyfills/modules/global');
const chalk = require("chalk");
const _suman = global.__suman = (global.__suman || {});
require('./add-suman-global-properties');
const ascii = require('./ascii');
const cwd = process.cwd();
const pkgJSON = require('../../package.json');
const v = pkgJSON.version;
_suman.log.info('Node.js version =>', process.version);
_suman.log.info(chalk.gray.italic(`Suman v${v} running individual test suite...`));
_suman.log.info('NODE_ENV =>', `"${process.env.NODE_ENV}"`);
_suman.log.info('cwd: ' + cwd);
console.log(ascii.suman_slant, '\n');
