#!/usr/bin/env node
'use strict';
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
const suman = require('suman');
const { Test } = suman.init(module);
Test.create(['semver', function (b, assert, describe, before, beforeEach, after, afterEach, it) {
        const semver = b.ioc.semver;
        console.log('semver => ', semver);
        before('adds foo', h => {
            return Promise.resolve('foo').then(function (v) {
                h.assert(v === 'foo');
                h.$inject.bar = v;
            });
        });
        it('sync test', t => {
            t.assert.equal(typeof null, 'object');
            t.assert.equal(t.$inject.bar, 'foo');
        });
        describe.parallel('nested block', b => {
            beforeEach('runs before each test', h => {
                console.log('test name is now running => ', h.test.desc);
            });
            it('async test', (t) => __awaiter(this, void 0, void 0, function* () {
                let foo = yield Promise.resolve(5);
                let bar = foo * (yield 4);
                t.assert.equal(bar, 20);
            }));
            it('async test', function* (t) {
                let foo = yield Promise.resolve(5);
                let bar = foo * (yield 4);
                t.assert.equal(bar, 20);
            });
            it.cb('async callback test', t => {
                setTimeout(function (err) {
                    t.done(err);
                }, 10);
            });
            const makeTest = function (apples) {
                return function (t) {
                    t.assert(apples === 'oranges');
                    setTimeout(t, 10);
                };
            };
            it.cb('async callback test', makeTest('oranges'));
        });
    }]);
